### ISSUE TITLE
Suggestion: Add column for fiat acceptance

### ISSUE THREAD

**Issue by DamageIncorporated** [pluja/kycnot#23]
Currently I use bisq for stacking my sats exclusively, but am always looking for alternatives, so this list is a great starting point.

What I am missing is a column for fiat currencies. The Value could be a short list (USD,EUR,YEN for example) or just a binary yes or no.

Many exchanges only allow to swap coins for coins but don't serve as a fiat on- or off-ramp, which is what I am looking for.

Thank you!

**Comment by pluja** [comment]
Seems good! I will work on it!
