### ISSUE TITLE
Extract data into YAML files

### ISSUE THREAD

**Issue by xaur** [pluja/kycnot#31]
Extracting data into YAML files will separate the data from the presentation and make changing both easier.

**Comment by pluja** [comment]
Yeah, this is something I really want to do. For now it's impossible to me as I don't have any time for myself and my projects. Anyone who wants to contribute is very welcome. I'm reviewing this repo and my github account every 2 days aprox.

**Comment by pluja** [comment]
Done in the new code version: b3b79397495437bc452799925e572a39c6b404e5

**Comment by xaur** [comment]
Awesome, thanks!

Small nit: the referenced commit adds a few `.pyc` files that I guess shouldn't be committed in the repo.

**Comment by pluja** [comment]
Yup, that's true. I just added a .gitignore to avoid this! Thanks!
