### ISSUE TITLE
RE: HodlHodl Exchange

### ISSUE THREAD

**Issue by dsalamau** [pluja/kycnot#32]
Hello!

We have checked your website, great to be listed there!

We have a few comments though, firsts of all we don’t require any person information for account creation purpose, as it is stated on the website.

Could you also explain what does the `X` mark in both XMR and Trade sections mean? Since we have Monero as a payment option and obviously we support Trading.

Best Regards,
David from HodlHodl

**Comment by pluja** [comment]
When I first made the platform, I was considering 'email' as personal information, but I'm changing it. As for the XMR and Trading, it was an error and I have just solved it, thanks for reporting! I think all of the reported issues are now solved.

**Comment by pluja** [comment]
Hey! I just removed the "XMR" tick from HodlHodl. I want to explain why. The tick means that you can operate with them (Buy / Sell) and not only use them.

I hope you understand my error and understand why I am doing it this way.
