### ISSUE TITLE
Remove XMR.to (shut down)

### ISSUE THREAD

**Issue by jonathancross** [pluja/kycnot#44]
XMR.to has shut down.

**Comment by pluja** [comment]
True!

**Comment by pluja** [comment]
Removed in 1d3f4731c6b510933cd0f827bb1785da39971ebe (I forgot to mention the issue on the comment)

**Comment by obeho** [comment]
@pluja This has to be delisted from the Services section too ig?

**Comment by pluja** [comment]
Oops, true. I will do that today. Thank you.

**Comment by pluja** [comment]
@obeho Oops, true. I will do that today. Thank you.

**Comment by obeho** [comment]
@pluja Can see it still on the website

**Comment by jonathancross** [comment]
@pluja @obeho Yep, still listed in services: https://kycnot.me/services.html

**Comment by pluja** [comment]
Done! @obeho @jonathancross
